### ISSUE TITLE
'Element' is imported from both 'package://...' and 'package://...'

### ISSUE THREAD

**Issue by alexcmgit** [acelords/flutter-starter-kit#2]
I am trying to resolve this issue below.
But I can't find the files originated in the error: "page.dart" and "navigator.dart" does anyone have an idea of what may be throwing this error?

Config:
Windows 10 Pro
Flutter Config:
```
Flutter 1.20.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bbfbf1770c (3 weeks ago) • 2020-08-13 08:33:09 -0700
Engine • revision 9d5b21729f
Tools • Dart 2.9.1
```

Copy & paste:
```
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/intro_views_flutter-2.8.0/lib/intro_views_flutter.dart:241:11: Error: 'Page' is imported from both 'package:flutter/src/widgets/navigator.dart' and 'package:intro_views_flutter/UI/page.dart'.
          Page(
          ^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/intro_views_flutter-2.8.0/lib/intro_views_flutter.dart:249:20: Error: 'Page' is imported from both 'package:flutter/src/widgets/navigator.dart' and 'package:intro_views_flutter/UI/page.dart'.
            child: Page(
                   ^^^^


FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 896

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

![Captura de Tela (30)](https://user-images.githubusercontent.com/51419598/92022822-c4520700-ed53-11ea-84f7-d6f754f4e53c.png)

**Comment by csciallano** [comment]
Exact same problem for me

**Comment by eejazishaq** [comment]
Exact same problem for me, pls update if anyone fixes this

**Comment by cmarfil** [comment]
+1, macOS in my case.

**Comment by chanhdatng** [comment]
+1, Did you guys solve this?

**Comment by EduardoFromTheFuture** [comment]
It's been a while since this issue is open. Nobody found a solution? It makes the project useless because build is not working.

**Comment by alexcmgit** [comment]
After searching a little, [I found this issue on `intro_views_flutter` package](https://github.com/aagarwal1012/IntroViews-Flutter/issues/69). Basically, the `intro_views_flutter` package use an duplicated import (import Page from `navigator` and other internal file), this issue occurs on `intro_views_flutter: ^2.8.0`, so to fix just change the target version to `intro_views_flutter: ^2.8.1`:

**In the `pubspec.yaml` change:**
```yaml
dependencies:
  # ... other deps

  # Remove this line
  intro_views_flutter: ^2.8.0

  # Add this line
  intro_views_flutter: ^2.8.1
```

[I opened a PR to fix this](https://github.com/acelords/flutter-starter-kit/pull/4), but although it was not merged, you can use the solution above.

**_After that there will only be a Google admob configuration issue, but it is not related with this issue problem._**

<sub>If someone have something to add, just reply, thx</sub>

**Comment by EduardoFromTheFuture** [comment]
Thank you very much for taking the time to debug this, your solution works! =)
