### ISSUE TITLE
Navigate login route when authentication token expired

### ISSUE THREAD

**Issue by cuongltv** [acelords/flutter-starter-kit#3]
I have a question when using your boilerplates, hope I can get solutions for my case.
In API base helper, when response has status code is 401 (token expired), how can I automatically navigate the login page.
![code](https://user-images.githubusercontent.com/64344924/97091351-99a27180-1665-11eb-8488-5b706d5b1bb1.png)
![code2](https://user-images.githubusercontent.com/64344924/97091353-9d35f880-1665-11eb-84d6-8960c9367ffe.png)

**Comment by syntaxlexx** [comment]
Hi there. Hoe you found a solution to your issue. 
For further enquiries, feel free to email me at [lexx@acelords.space](mailto:lexx@acelords.space).

Cheers.
